export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE'
}

export enum CivilStatus {
  SINGLE = 'SINGLE',
  MARRIED = 'MARRIED',
  WIDOWED = 'WIDOWED',
  DIVORCED = 'DIVORCED',
  ANNULLED = 'ANNULLED',
  UNKNOWN = 'UNKNOWN',
  LIVE_IN = 'LIVE_IN'
}

export enum Suffix {
  JR = 'JR',
  SR = 'SR',
  I = 'I',
  II = 'II',
  III = 'III',
  OTHER = 'OTHER'
}

export enum WorkStatus {
  EMPLOYED = 'EMPLOYED',
  UNEMPLOYED = 'UNEMPLOYED',
  SELF_EMPLOYED = 'SELF_EMPLOYED',
  CURRENTLY_LOOKING = 'CURRENTLY_LOOKING',
  NOT_INTERESTED = 'NOT_INTERESTED'
}

export enum YouthClassificationType {
  IN_SCHOOL_YOUTH = 'IN_SCHOOL_YOUTH',
  OUT_OF_SCHOOL_YOUTH = 'OUT_OF_SCHOOL_YOUTH',
  WORKING_YOUTH = 'WORKING_YOUTH',
  PERSON_WITH_DISABILITY = 'PERSON_WITH_DISABILITY',
  CHILDREN_IN_CONFLICT_LAW = 'CHILDREN_IN_CONFLICT_LAW',
  INDIGENOUS_PEOPLE = 'INDIGENOUS_PEOPLE'
}

export enum EducationBackground {
  ELEMENTARY_LEVEL = 'ELEMENTARY_LEVEL',
  ELEMENTARY_GRADUATE = 'ELEMENTARY_GRADUATE',
  HIGH_SCHOOL_GRADUATE = 'HIGH_SCHOOL_GRADUATE',
  VOCATIONAL_GRAD = 'VOCATIONAL_GRAD',
  COLLEGE_LEVEL = 'COLLEGE_LEVEL',
  COLLEGE_GRADUATE = 'COLLEGE_GRADUATE',
  MASTERS_LEVEL = 'MASTERS_LEVEL',
  MASTERS_GRADUATE = 'MASTERS_GRADUATE',
  DOCTOR_LEVEL = 'DOCTOR_LEVEL',
  DOCTOR_GRADUATE = 'DOCTOR_GRADUATE'
}

export enum DocumentType {
  PROFILE_PICTURE = 'Profile Picture',
  VALID_ID = 'Valid ID',
  OTHER = 'Other'
}

export enum ConcernType {
  PROJECT_CONCERN = 'PROJECT_CONCERN',
  COMMUNITY_CONCERN = 'COMMUNITY_CONCERN',
  SYSTEM_CONCERN = 'SYSTEM_CONCERN'
}

export enum ConcernStatus {
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED'
}

export enum TaskStatus {
  PRIO = 'PRIO',
  TODO = 'TODO',
  IN_PROGRESS = 'IN_PROGRESS',
  DONE = 'DONE',
  CUSTOM = 'CUSTOM'
}

export enum Tasking {
  PUBLICATION_COMMITTEE = 'PUBLICATION_COMMITTEE',
  LETTERS_COMMUNCATION = 'LETTERS_COMMUNCATION',
  HOST_EMCEE = 'HOST_EMCEE',
  TECHNICAL = 'TECHNICAL',
  PRINTING_OF_CERTIFICATES = 'PRINTING_OF_CERTIFICATES',
  DOCUMENTATION = 'DOCUMENTATION',
  LOGISTICS = 'LOGISTICS'
}